# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("OTP_REQUESTED", "OTP requested"),
                            ("OTP_VERIFIED", "OTP verified"),
                            ("OTP_FAILED", "OTP failed"),
                            ("OTP_LOCKED", "OTP locked"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="audit_evt_created_idx"
                    )
                ],
            },
        ),
    ]
