# Generated by Django 6.0.2 on 2026-03-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_event_07f862_idx",
            old_name="audit_evt_created_idx",
        ),
    ]
